import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {contactForm} from './contact-form.mjs';
import {LINKS} from './config.mjs';
const groups=[
 {id:'website',label:'HPでの商品紹介',category:'本ページでの商品紹介',lead:'暮らしの備えを探す人へ、商品を届ける。',description:'備えニキHPの掲載場所を選べます。商品名のリンクから販売ページへ誘導し、用途や特徴を伝えます。',plans:[
 ['stock','備蓄リストへの掲載','5,500','掲載30日','水・食料・衛生用品など、商品の用途に合うカテゴリーへ掲載。','商品名・販売ページへのリンク・短い紹介文'],
 ['card','商品紹介カード','22,000','掲載30日','トップの防災リュック・ポタ電の並びに、PR商品用の紹介枠を追加。','紹介画像・商品説明・商品リンク'],
 ['detail','詳細紹介ページ','44,000','制作33,000円＋掲載30日11,000円','商品の特徴や使いどころをまとめた専用ページを作り、トップから誘導。','専用ページ制作・紹介画像・商品説明・商品リンク'],
 ['hero','メイン画像での紹介','55,000','制作33,000円＋掲載7日22,000円','トップのメイン画像で、備えニキが商品を持つ・着るなどの演出。','専用イラスト制作・トップ掲載／1社限定・期間限定']
 ]},
 {id:'instagram',label:'Instagramでの紹介',category:'Instagramでの商品・サービス紹介',lead:'商品の魅力を、いつもの発信の中で。',description:'画像をじっくり読めるフィード、動きで伝えるリール、リンクへ誘導するストーリーズ。目的に合わせて選べます。',plans:[
 ['feed','フィード紹介','33,000','1投稿','商品画像と説明を組み合わせ、特徴や使いどころを紹介。','画像制作＋フィード投稿1回'],
 ['reel','リール紹介','55,000','1投稿','構成から動画制作まで行い、備えニキのInstagramへ投稿。','動画制作＋リール投稿1回'],
 ['reel-story','リール＋ストーリーズ','66,000','リール1本＋ストーリーズ3枚','リールで興味を持ってもらい、ストーリーズで商品ページへ誘導。','リール制作・投稿＋ストーリーズ制作・投稿'],
 ['full','まとめて紹介セット','88,000','フィード1投稿＋リール1本＋ストーリーズ3枚','動画・画像・リンク誘導を組み合わせた紹介プラン。','フィード・リール・ストーリーズの制作と投稿']
 ]},
 {id:'video',label:'動画制作',category:'動画制作のご相談',lead:'伝えたいことを、わかりやすいショート動画に。',description:'普段の発信のように、構成・字幕・ナレーションで伝える縦型動画を制作。完成した動画データを納品します。',plans:[
 ['one','ショート動画 1本','33,000','1本あたり33,000円','まずは1本、商品やサービスの紹介動画を作りたい方へ。','30〜60秒の縦型動画／構成・編集・字幕・ナレーション'],
 ['five','ショート動画 5本','110,000','1本あたり22,000円・単品比 約33％OFF','同じテイストで、複数のテーマをまとめて制作。','30〜60秒×5本／構成・編集・字幕・ナレーション'],
 ['ten','ショート動画 10本','198,000','1本あたり19,800円・単品比40％OFF','継続的な発信に向けて、まとまった本数を準備したい方へ。','30〜60秒×10本／構成・編集・字幕・ナレーション']
 ]}
];
const diagrams=`<div class="placement-guide"><div class="mini-page" aria-label="HPの掲載場所のイメージ"><div class="mini-brand">備えニキ</div><div class="mini-hero"><img src="/assets/niki-helmet-gray-approved-v1.png" alt="メイン画像での紹介位置" loading="lazy"><span>04 メイン画像<br><small>商品を持つ・着る演出</small></span></div><div class="mini-cards"><div>防災リュック</div><div>ポタ電</div><div class="mini-pr">02 PR商品</div></div><div class="mini-row">01 備蓄リスト内の商品紹介</div><div class="mini-row">03 詳細紹介ページへのリンク →</div></div><div><span class="eyebrow">PLACEMENT GUIDE</span><h3>掲載場所が選べます。</h3><p>トップで大きく見せる紹介から、備蓄カテゴリー内の紹介まで。商品とご予算に合う場所をご提案します。</p><p class="work-note">図は掲載位置のイメージです。掲載時はPR・広告であることを明示します。</p><a class="text-link" href="/design-preview/#essentials">実際のHPを見る ↗</a></div></div>`;
const conditions={website:'掲載期間は公開日から起算します。期間終了後は掲載枠を終了し、メイン画像は通常の画像に戻します。延長は別途ご相談ください。制作内容・画像の修正範囲はお見積もり時に確認します。商品に合うカテゴリーがない場合は掲載場所をご相談します。トップ画像での演出はイラストによる表現です。',instagram:'商品代・送料はご依頼者様のご負担となります。投稿内容・公開時期・掲載期間・修正範囲は事前に確認します。ストーリーズは通常24時間の掲載です。投稿を企業アカウントに転載する場合や広告に利用する場合は、利用範囲と期間に応じて別途お見積もりします。',video:'各動画の修正は1回まで含みます。5本・10本プランは、まとめてのご発注・素材提供と共通の制作テイストが条件です。撮影、複雑な生成映像、追加修正、広告利用は別途お見積もりします。備えニキのInstagramへの投稿は含まれません。納期・納品形式・利用範囲は事前に確認します。'};
function gallery(title, description, names, style='') {
 return `<div class="case-gallery"><h4>${title}</h4><p>${description}</p><div class="case-images ${style}">${names.map(([name,caption])=>`<figure><a href="/assets/work-examples/${name}.jpg" class="case-zoom" aria-label="${caption}を拡大"><img src="/assets/work-examples/${name}.jpg" alt="${caption}" width="${name.startsWith('feed')?886:name==='story-single'?768:name==='story-1'?665:724}" height="${name.startsWith('feed')?886:name==='story-single'?1024:name==='story-1'?1182:1086}" loading="lazy"></a><figcaption>${caption}</figcaption></figure>`).join('')}</div></div>`;
}
const instagramCase=`<section class="case-study"><span class="eyebrow">INSTAGRAM / 制作・投稿実例</span><h3>野菜スープの商品紹介</h3><p class="work-note">※紹介している野菜スープは、WE VEGETABLE様よりギフト提供いただいた商品です。</p><p>商品提供を受けて制作・投稿した、フィードとストーリーズの実例です。備蓄を紹介する企画の中で野菜スープを取り上げ、商品の特徴や使う場面をイラストで伝えています。</p><p class="work-note">画像をタップすると拡大できます。画像内の順位は当時の投稿企画の表現です。</p>${gallery('フィード投稿','一覧から個別紹介、暮らしの中の使い方まで、5枚で見せる構成。',[['feed-1','備蓄TOP10の一覧'],['feed-2','長期保存パンの紹介'],['feed-3','缶詰の紹介'],['feed-4','野菜スープの紹介'],['feed-5','日常と非常時の使い方']])}${gallery('連続ストーリーズ','ランキング形式の連続投稿から、野菜スープを含む上位3枚を抜粋。',[['story-3','3位：野菜スープ'],['story-2','2位：缶詰'],['story-1','1位：長期保存パン']],'portrait-gallery')}${gallery('単発ストーリーズ','1枚で商品とメッセージを見せる、野菜スープ単独の紹介。',[['story-single','野菜スープの単発ストーリーズ']],'single-gallery')}</section>`;
const reelExample=`<section class="reel-example" id="reel-example"><div><span class="eyebrow">REEL / 制作・投稿実例</span><h3>リール動画の実例</h3><p>映像のテンポ、字幕、ナレーションなど、実際の投稿で仕上がりをご覧ください。</p><a class="text-link" href="https://www.instagram.com/reel/Dc-vNP7B18S/" target="_blank" rel="noopener noreferrer">Instagramで動画を見る ↗</a><p class="work-note">埋め込みが表示されない場合は、上のリンクからご覧いただけます。</p></div><details class="reel-player"><summary>ページ内で動画を見る <span>＋</span></summary><iframe src="https://www.instagram.com/reel/Dc-vNP7B18S/embed/" title="備えニキのリール投稿実例" loading="lazy" allow="encrypted-media; fullscreen" referrerpolicy="strict-origin-when-cross-origin"></iframe></details></section>`;
function section(g){return `<section class="work-section" id="${g.id}"><div class="work-section-head"><span class="eyebrow">0${groups.indexOf(g)+1} / SERVICE</span><h2>${g.label}</h2><h3>${g.lead}</h3><p>${g.description}</p></div>${g.id==='website'?diagrams:''}<div class="price-grid ${g.id==='video'?'three':''}">${g.plans.map(([id,title,price,period,desc,includes])=>`<article class="price-card"><span class="eyebrow">${g.id==='website'?'0'+(g.plans.findIndex(p=>p[0]===id)+1)+' / ':''}${g.label}</span><h3>${title}</h3><p class="plan-price">${price}<small>円（税込）</small></p><p class="plan-period">${period}</p><p>${desc}</p><div class="plan-includes"><small>含まれる内容</small><p>${includes}</p></div><a class="btn plan-select" href="#contact" data-category="${g.category}" data-plan="${title}（${price}円・税込）">このプランで相談する <span>→</span></a></article>`).join('')}</div>${g.id==='instagram'?instagramCase+reelExample:''}${g.id==='video'?`<div class="work-examples"><div><span class="eyebrow">${g.id==='instagram'?'INSTAGRAM':'VIDEO'} STYLE</span><h3>${g.id==='instagram'?'発信の雰囲気を見る':'動画のテイストを見る'}</h3><p>備えニキのInstagramで、普段の${g.id==='instagram'?'投稿':'動画'}をご覧いただけます。</p></div><a class="text-link" href="#reel-example">リールの制作実例を見る ↑</a></div>`:''}<details class="work-conditions"><summary>掲載・制作の条件 <span>＋</span></summary><p>${conditions[g.id]}</p></details></section>`;}
export function buildWorkPage(home){
const head=home.slice(0,home.indexOf('<body>')).replace('備えニキ｜HPデザインプレビュー','お仕事のご案内・料金｜備えニキ').replace('</head>',`<style>${readFileSync('assets/work.css','utf8')}</style></head>`);
const header=home.match(/<header>[\s\S]*?<\/header>/)[0].replaceAll('href="#','href="/design-preview/#');
const footer=home.match(/<footer>[\s\S]*?<\/footer>/)[0];
const html=`${head}<body class="work-page">${header}<main><section class="work-hero wrap"><div><a class="text-link" href="/design-preview/">← 備えニキHP</a><span class="eyebrow">WORK WITH SONAE NIKI</span><h1>商品の魅力を、<br>備えるきっかけに。</h1><p>HPでの商品紹介、Instagramでの発信、動画制作。<br>目的に合わせて選べる、お仕事のメニューです。</p><p class="work-note">料金はすべて税込。ご相談・お見積もりの段階でお支払いは発生しません。</p></div><img src="/assets/niki-profile-approved-v1.png" width="1122" height="1402" alt="備えニキのプロフィールイラスト"></section><nav class="work-nav" aria-label="お仕事メニュー">${groups.map(g=>`<a href="#${g.id}">${g.label}</a>`).join('')}</nav><div class="wrap work-content">${groups.map(section).join('')}<section class="work-flow"><span class="eyebrow">HOW IT WORKS</span><h2>ご相談から公開・納品まで</h2><ol><li><strong>ご相談</strong><p>商品・サービス、ご希望のプランと時期をお知らせください。</p></li><li><strong>内容・お見積もりの確認</strong><p>掲載場所、制作範囲、納期や利用条件を確認して確定します。</p></li><li><strong>制作・ご確認</strong><p>構成や紹介内容をご確認いただき、制作を進めます。</p></li><li><strong>公開・納品</strong><p>合意した内容に沿って、掲載・投稿または動画を納品します。</p></li></ol><p class="work-note">商品の内容によってはお受けできない場合があります。追加費用が必要な場合は、着手前にお見積もりします。</p><p class="gift-invitation">商品のギフト提供のみのご相談も歓迎しています。<br>プランやご予算が決まっていなくても、まずはお気軽にご相談ください。</p><button class="btn contact-toggle" type="button" aria-expanded="false" aria-controls="contact">プランが未定でも相談する <span aria-hidden="true">＋</span></button></section></div>${contactForm}</main>${footer}<dialog class="case-dialog" aria-label="制作実例の拡大画像"><button type="button" class="case-close" autofocus aria-label="拡大画像を閉じる">閉じる ×</button><img alt=""></dialog><script src="/assets/work.js" defer></script><script src="/assets/contact.js" defer></script></body></html>`;
mkdirSync('public/design-preview/work',{recursive:true});writeFileSync('public/design-preview/work/index.html',html);
}
